FROM node:20-slim AS builder

RUN apt-get update && apt-get install -y \
    zlib1g-dev libpng-dev build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /usr/src/app

COPY package* ./

RUN npm install 

COPY . .

RUN npm run build

FROM nginx:alpine

WORKDIR /app

COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

