FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package* ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package* ./

RUN npm install --only=production

EXPOSE 3000

CMD ["node" ,"dist/index.js"]