export const config = {
    API_BASE_URL: __ENV.API_BASE_URL || 'http://localhost:3000',
    FRONTEND_URL: __ENV.FRONTEND_URL || 'http://localhost:5173',
    AUTH0_DOMAIN: __ENV.AUTH0_DOMAIN,
    AUTH0_CLIENT_ID: __ENV.AUTH0_CLIENT_ID,
    AUTH0_CLIENT_SECRET: __ENV.AUTH0_CLIENT_SECRET,
    AUTH0_AUDIENCE: __ENV.AUTH0_AUDIENCE,
}